### ISSUE TITLE
open-source question

### ISSUE THREAD

**Issue by JonathanTippy** [Wooty-B/LX2K_Guide#10]
Thanks for this great guide! I'm wondering weather the LX2K can be booted with only open-source firmare + software because I believe this is important for anybody's security. So far, I have had no luck finding any information on the subject. If U-boot is necessary for this, are there any drawbacks in GPU compatibility? Currently I'm using a rockpro64 and I'm overall pleasantly surprised with how well it works, but also not happy with the memory limitation. Most of the time I'm using swap, which is not good for my ssd. Also some recent changes to steam / box64 have increased the minimum memory so steam is no longer possibly.

**Comment by IoanaCiornei** [comment]
The LX2K board uses the NXP LX2160A SoC which, unfortunately for your use case, uses a closed source firmware named Management Complex (MC) for the configuration of the networking accelerators. For more information, you can search for DPAA2 - Data Path Acceleration Architecture 2.
