### ISSUE TITLE
you managed to run TheDarkMod on arm64?

### ISSUE THREAD

**Issue by marioseixas** [Wooty-B/LX2K_Guide#11]
i'm using an rockchip rk3588 with Mali-G610 MC4 as GPU on Debian 11. octa-core and 32gb RAM.

it is possible to run steam and thedarkmod?

**Comment by Wooty-B** [comment]
Apologies for late, very late reply, life happened... However yes, TheDarkMod should run as I recall, and assuming now should be much further along the way! If you have any questions related to this guide please let me know. Thanks!
