### ISSUE TITLE
mesa patch MR

### ISSUE THREAD

**Issue by okias** [Wooty-B/LX2K_Guide#8]
Hello, is there somewhere in the official https://gitlab.freedesktop.org/mesa/mesa/ repository merge request with this patch?

Was there any effort to upstream it?

**Comment by Wooty-B** [comment]
I am currently using Linux kernel 5.14.0 and Mesa 20.3.5 from git with patches applied, and haven't tested this as of yet. However, I am about to install Debian Bullseye to another drive and testing a newer kernel and will certainly update this thread with my findings.

**Comment by okias** [comment]
I wrote to the developer who created the patch and currently it shouldn't be needed at all. For possible performance gain under Xorg (deprected) or XWayland, can be used, but otherwise can be omitted.
