### ISSUE TITLE
Cannot get SFP+ ports to work

### ISSUE THREAD

**Issue by xnuken** [Wooty-B/LX2K_Guide#9]
I cannot get the 4 SFP+ ports on my Honeycomb to work at all using Fedora 37 

Kernel`6.1.9-200.fc37.aarch64`
Grub Config`GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="iommu.passthrough=1 arm-smmu.disable_bypass=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true`
Output of ls-addni dpmac.9 `[aarch64@CEX7 ~]$ sudo ls-addni dpmac.9
MC error: Unsupported operation (status 0xb)`

**Comment by Wooty-B** [comment]
Try using the latest SolidRun kernel:

1. Pull kernel:
     - git clone https://github.com/SolidRun/linux-stable.git && cd linux-stable
2. Switch to latest branch:
     - git switch linux-6.1.y-cex7-dev
3. Compile & Install Kernel:
     - cp -v /boot/config-$(uname -r) .config
     - scripts/config --disable SYSTEM_TRUSTED_KEYS
     - scripts/config --disable SYSTEM_REVOCATION_KEYS
     - make menuconfig
     - make -j16
     - make Image
     - sudo make modules_install
     - sudo make install
     - sudo update-initramfs -c -k 6.1.3+
     - sudo update-grub

The kernel above contains many patches, so please let me know if this works and I will update my guide.

**Comment by xnuken** [comment]
How do I get the ports to automatically come up on boot so I do not have to do it manually on Fedora 38

**Comment by xnuken** [comment]
Never mind that figured it out but they keep mapping to different interfaces when the system is rebooted which is very annoying and breaks my use case is there anyway to solve this.

**Comment by IoanaCiornei** [comment]
You can use some udev rules to statically configure the names of the interfaces. Below is a snippet of my udev file.

```
root@localhost:~# cat /etc/udev/rules.d/74-fsl-dpaa2-persistent-networking.rules
SUBSYSTEM=="net", ACTION=="add|change|online|offline|change", DRIVERS=="fsl_dpaa2_eth", ENV{OF_FULLNAME}=="/soc/fsl-mc@80c000000/dpmacs/ethernet@1", NAME="endpmac1"
SUBSYSTEM=="net", ACTION=="add|change|online|offline|change", DRIVERS=="fsl_dpaa2_eth", ENV{OF_FULLNAME}=="/soc/fsl-mc@80c000000/dpmacs/ethernet@2", NAME="endpmac2"
SUBSYSTEM=="net", ACTION=="add|change|online|offline|change", DRIVERS=="fsl_dpaa2_eth", ENV{OF_FULLNAME}=="/soc/fsl-mc@80c000000/dpmacs/ethernet@3", NAME="endpmac3"
```

**Comment by Wooty-B** [comment]
Late, but marking as resolved. Thanks @IoanaCiornei !!!
